
development:
  adapter: postgresql
  encoding: unicode
  database: listiglio_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: listiglio_production
  pool: 5
  username: postgres
  password:
